[package]

name = "interleaver"
version = "0.0.1"
authors = ["Mark Christiaens <mark.g.j.christiaens@gmail.com>"]

[dependencies.docopt]

git = "https://github.com/docopt/docopt.rs"

[dependencies.docopt_macros]

git = "https://github.com/docopt/docopt.rs"
